name: pytest

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  pytest:
    strategy:
      matrix:
        os:
          - label: Linux
            runner: ubuntu-latest
          - label: macOS
            runner: macos-latest

        deps:
          - label: Latest
            spec: ""
          - label: Minimum
            spec: |
              python=3.8
              numpy=1.20
              numba=0.54
              h5py=3.5
              ruamel_yaml=0.15
              pydantic=1.10
              pymp-pypi=0.5
              gdal=3.4

      fail-fast: false
    name: ${{ matrix.os.label }} â€¢ ${{matrix.deps.label }}
    runs-on: ${{ matrix.os.runner }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: requirements.txt
          environment-name: dolphin
          extra-specs: ${{ matrix.deps.spec }}
          channels: conda-forge
      - name: Install
        run: |
          pip install --no-deps .
      - name: Test
        run: |
          micromamba install -f test/requirements.txt -c conda-forge
          pytest --cov-report=xml
      - name: Coverage report
        uses: codecov/codecov-action@v2
